# Basic Data Structures

### Tuples

In [4]:
t = (1, 2.5, 'data') #()
type(t)

tuple

In [5]:
t = 1, 2.5, 'data'
type(t)

tuple

In [7]:
t[2]

'data'

In [8]:
type(t[2])

str

In [9]:
type(t[1])

float

In [10]:
t.count('data')

1

In [11]:
t.index(1)

0

### Lists

In [12]:
l = [1, 2.5, 'data'] #[]
l

[1, 2.5, 'data']

In [13]:
l[2]

'data'

In [14]:
type(l)

list

In [15]:
l.append([4,3]) #list추가
l

[1, 2.5, 'data', [4, 3]]

In [16]:
l.extend([1.0, 1.5, 2.0]) #개별 elements 추가
l

[1, 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [18]:
l.insert(1, 'insert') #1번째에 insert 삽입
l

[1, 'insert', 2.5, 'data', [4, 3], 1.0, 1.5, 2.0]

In [19]:
l.remove('data')
l

[1, 'insert', 2.5, [4, 3], 1.0, 1.5, 2.0]

In [20]:
l.remove([4,3])
l

[1, 'insert', 2.5, 1.0, 1.5, 2.0]

In [21]:
p = l.pop(3) #네번째에 잇는 1을 삭제
print(l, p)

[1, 'insert', 2.5, 1.5, 2.0] 1.0


In [22]:
l[2:5]

[2.5, 1.5, 2.0]

### Excursion : Control Structures

In [24]:
for element in l[2:5]:
    print(element ** 2)

6.25
2.25
4.0


In [25]:
r = range(0, 8, 1) #start / end / step width
r

range(0, 8)

In [26]:
type(r)

range

In [28]:
for i in range(2,5):
    print(l[i]**2)

6.25
2.25
4.0


In [29]:
for i in range(1,10):
    if i % 2 == 0:
        print("%d is even" % i)
    elif i % 3 == 0:
        print("%d is multiple of 3" % i)
    else:
        print("%d is odd" % i)

1 is odd
2 is even
3 is multiple of 3
4 is even
5 is odd
6 is even
7 is odd
8 is even
9 is multiple of 3


In [30]:
total = 0 
while total < 100:
    total += 1
print(total)

100


In [31]:
m = [i ** 2 for i in range(5)]
m

[0, 1, 4, 9, 16]

### Excursion: Functional Programming

In [32]:
def f(x):
    return x **2 
f(4)

16

In [33]:
def even(x):
    return x % 2 == 0
even(3)

False

In [34]:
list(map(lambda x : x ** 2, range(10)))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [35]:
list(filter(even, range(15)))

[0, 2, 4, 6, 8, 10, 12, 14]

### Dicts

In [43]:
d = {                             #key/Values
    'name': 'Angela Merkel',
    'country': 'Germany',
    'Profession': 'Chancelor',
    'Age': 60
}
type(d)

dict

In [40]:
print(d['name'], d['Age'])

Angela Merkel 60


In [41]:
d.keys()

dict_keys(['name', 'country', 'Profession', 'Age'])

In [42]:
d.values()

dict_values(['Angela Merkel', 'Germany', 'Chancelor', 60])

In [44]:
d.items()

dict_items([('name', 'Angela Merkel'), ('country', 'Germany'), ('Profession', 'Chancelor'), ('Age', 60)])

In [45]:
birthday = True
if birthday is True:
    d['Age'] += 1
print(d['Age'])

61


In [46]:
for item in d.items():
    print(item)

('name', 'Angela Merkel')
('country', 'Germany')
('Profession', 'Chancelor')
('Age', 61)


### Sets

In [47]:
s = set(['u', 'd', 'ud', 'du', 'd', 'du']) #겹치기 x
s

{'d', 'du', 'u', 'ud'}

In [48]:
t = set(['d','dd','uu','u'])

In [49]:
s.union(t) #s + t

{'d', 'dd', 'du', 'u', 'ud', 'uu'}

In [51]:
s.intersection(t) #교집합

{'d', 'u'}

In [53]:
s.difference(t) #in s but not t

{'du', 'ud'}

In [54]:
t.difference(s)

{'dd', 'uu'}

In [55]:
s.symmetric_difference(t) #in either one but not both(서로 없는 것 合)

{'dd', 'du', 'ud', 'uu'}

In [56]:
from random import randint
l = [randint(0,10) for i in range(1000)]
len(l)

1000

In [57]:
l[:20]

[8, 4, 10, 4, 0, 1, 3, 5, 1, 4, 0, 3, 9, 6, 4, 1, 10, 5, 4, 6]

In [58]:
s = set(l)
s

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

### Numpy Data Structures

#### Arrays with Python Lists

In [59]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]

In [60]:
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [61]:
m[1]

[0.5, 0.75, 1.0, 1.5, 2.0]

In [62]:
m[1][0]

0.5

In [63]:
v1 = [0.5, 1.5]
v2 = [1,2]
m = [v1,v2]
c = [m,m]
c

[[[0.5, 1.5], [1, 2]], [[0.5, 1.5], [1, 2]]]

In [64]:
m

[[0.5, 1.5], [1, 2]]

In [65]:
c[1][1][0]

1

In [66]:
v = [0.5, 0.75, 1.0, 1.5, 2.0]
m = [v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [67]:
v[0] = 'Python'
m

[['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0],
 ['Python', 0.75, 1.0, 1.5, 2.0]]

#### Regular NumPy Arrays

In [68]:
import numpy as np

In [69]:
a = np.array([0,0.5,1.0,1.5,2.0])
type(a)

numpy.ndarray

In [70]:
a[:2] #1 to 2 choice

array([0. , 0.5])

In [71]:
a.sum()

5.0

In [72]:
a.std()

0.7071067811865476

In [74]:
a.cumsum() #cummulative sum

array([0. , 0.5, 1.5, 3. , 5. ])

In [75]:
a*2

array([0., 1., 2., 3., 4.])

In [76]:
a**2

array([0.  , 0.25, 1.  , 2.25, 4.  ])

In [77]:
np.sqrt(a)

array([0.        , 0.70710678, 1.        , 1.22474487, 1.41421356])

In [78]:
b = np.array([a, a*2])

In [79]:
b

array([[0. , 0.5, 1. , 1.5, 2. ],
       [0. , 1. , 2. , 3. , 4. ]])

In [80]:
b[0]

array([0. , 0.5, 1. , 1.5, 2. ])

In [81]:
b[0,2]

1.0

In [82]:
b.sum()

15.0

In [83]:
b.sum(axis = 1) #행 合

array([ 5., 10.])

In [84]:
b.sum(axis = 0) #열 合

array([0. , 1.5, 3. , 4.5, 6. ])

In [85]:
c = np.zeros((2,3,4), dtype = 'i', order = 'C')
c #2차원 / 3x4 행렬

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [88]:
d = np.ones_like(c, dtype = 'f')
d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)

In [89]:
import random
i = 5000

In [90]:
i

5000

#### Structured Arrays

In [91]:
dt = np.dtype([('Name', 'S10'), ('Age', 'i4'),
              ('Height', 'f'), ('Children/Pets', 'i4', 2)])
s = np.array([('Smith', 45, 1.83, (0,1)),
             ('Jones', 53, 1.72, (2,2))], dtype = dt)
s

array([(b'Smith', 45, 1.83, [0, 1]), (b'Jones', 53, 1.72, [2, 2])],
      dtype=[('Name', 'S10'), ('Age', '<i4'), ('Height', '<f4'), ('Children/Pets', '<i4', (2,))])

In [92]:
s['Name']

array([b'Smith', b'Jones'], dtype='|S10')

In [94]:
s['Height'].mean()

1.7750001

In [95]:
s[1]['Age']

53

### Vectorization of Code

#### Basic Vectorization

In [96]:
r = np.random.standard_normal((4,3))
s = np.random.standard_normal((4,3))

In [97]:
r + s

array([[ 0.34587844,  0.62786768,  0.08968843],
       [-0.52598394, -0.87931212, -2.16978486],
       [-1.44446319,  1.86977278, -0.72348894],
       [ 1.5329842 ,  1.22013504, -2.16212768]])

In [98]:
2 * r + 3

array([[2.13587616, 2.2605872 , 4.36913622],
       [2.46198994, 3.36659826, 2.62671716],
       [3.37857201, 5.64517234, 2.87041007],
       [2.926609  , 2.71808266, 1.43372948]])

In [99]:
s = np.random.standard_normal(3)

In [100]:
r + s

array([[-0.61906554, -0.16725935,  1.39216838],
       [-0.45600865,  0.38574618,  0.52095885],
       [ 0.00228239,  1.52503322,  0.6428053 ],
       [-0.22369912,  0.06148839, -0.07553499]])

In [101]:
s

array([-0.18700362,  0.20244705,  0.70760027])

In [105]:
def f(x):
    return 3 * x + 5

In [107]:
f(0.5) #float array

6.5

In [109]:
f(r) #numpy array

array([[3.70381425, 3.8908808 , 7.05370433],
       [4.19298492, 5.54989738, 4.44007574],
       [5.56785802, 8.96775851, 4.8056151 ],
       [4.8899135 , 4.57712399, 2.65059422]])

In [110]:
np.sin(r) #array as input

array([[-0.41874413, -0.36134169,  0.63233849],
       [-0.26577238,  0.18227442, -0.1855597 ],
       [ 0.1881577 ,  0.96935368, -0.06474964],
       [-0.03668726, -0.14049234, -0.70550486]])

In [111]:
np.sin(np.pi) #float as input

1.2246467991473532e-16