## ndrayy class

In [145]:
import numpy as np

In [3]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
print(type(a))
a
#like list

<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
L = [0,1,2,3,4,5,6,7,8,9]
print(type(L))
L

<class 'list'>


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

### list - Linked list 와 같은 형태 , 각각의 원소가 다른 자료형
### ndrray - 연속적인 메모리 배치, 각각의 원소가 같은 자료형

In [10]:
a = np.arange(1000)
%time a

Wall time: 0 ns


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [12]:
L = range(1000)
L

range(0, 1000)

In [25]:
L = range(10)
print(L)

range(0, 10)


In [24]:
a = [1,2,3,4,5]
type(a)

list

In [20]:
a*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

## 다차원 행렬

In [29]:
a = np.array([0,1,2])
a

array([0, 1, 2])

In [31]:
b = np.array([[0,1,2], [3,4,5]]) #2x3
b

array([[0, 1, 2],
       [3, 4, 5]])

In [36]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #2x2x2
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [38]:
print(c.ndim) #3차원
print(c.shape) #2x2x2

3
(2, 2, 2)


## 다차원 행렬 Indexing

In [39]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [40]:
a[0,0]

0

In [41]:
a[0,2]

2

In [42]:
a[-1,-1]

5

## 다차원 행렬 Slicing

In [44]:
a = np.array([[0,1,2,3,],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
a[0,:] #첫째행 전체

array([0, 1, 2, 3])

In [48]:
a[:,1] #두번째열 전체

array([1, 5])

In [49]:
a[1,1:] #두번째 행의 두번째 열부터 all

array([5, 6, 7])

## 행렬 Indexing

### Boolean 행렬 
### Integer 행렬

In [51]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [52]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [54]:
a = np.array([[0,1,2,3,4], [5,6,7,8,9]])
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

# Numpy 자료형

In [56]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [57]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [59]:
x = np.array([1,2,3], dtype = 'f')
x.dtype

dtype('float32')

In [60]:
x[0] + x[1]

3.0

In [63]:
x = np.array([1,2,3], dtype = 'U')
x.dtype #u = 유니코드

dtype('<U1')

In [62]:
x[0] + x[1]

'12'

## Inf / NaN

In [65]:
np.array([0,1,-1,0]) / np.array([1,0,0,0])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([  0.,  inf, -inf,  nan])

In [66]:
np.log(0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [67]:
np.exp(-np.inf)

0.0

## 배열

#### Zeros , Ones
#### Zeros_like , Ones_like
#### empty
#### arange
#### linspace , logspace
#### rand, randn

In [71]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [72]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
c = np.zeros((5,2), dtype = "i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [75]:
d = np.zeros(5, dtype = "U4")
d

array(['', '', '', '', ''], dtype='<U4')

In [76]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [77]:
e = np.ones((2,3,4), dtype = "i8")
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [78]:
f = np.ones_like(b, dtype = "f")
f

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [80]:
g = np.empty((4,3))
g

array([[8.57804315e-312, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.31370903e-076],
       [5.58172497e-091, 9.60074714e-071, 8.46044116e+164],
       [1.72006370e+184, 6.48224659e+170, 4.93432906e+257]])

In [81]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [85]:
np.arange(3, 21, 2) #시작 / 끝(포함x) / jump

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [86]:
np.linspace(0,100, 5) #시작 / 끝(포함o) / 개수

array([  0.,  25.,  50.,  75., 100.])

In [87]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## 전치

In [88]:
A = np.array([[1,2,3], [4,5,6]]) #2x3
A

array([[1, 2, 3],
       [4, 5, 6]])

In [89]:
A.T #3x2

array([[1, 4],
       [2, 5],
       [3, 6]])

## 크기변환

In [90]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [94]:
b = a.reshape(3,4) #개수가 맞아야함
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [95]:
a.reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [99]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [101]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [102]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [103]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [104]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [106]:
x[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

# 배열 연결
### hstack
### vstack
### dstack
### stack
### tile

In [107]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
a2 = np.zeros((2,2))
a2

array([[0., 0.],
       [0., 0.]])

In [110]:
np.hstack([a1,a2]) #두 행렬의 행의 개수가 같아야

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [111]:
b1 = np.ones((2,3))
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [113]:
b2 = np.zeros((3,3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [114]:
np.vstack([b1,b2]) #두 행렬의 열의 개수가 같아야

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [115]:
c1 = np.ones((3,4))
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [116]:
c2 = np.zeros((3,4))
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [117]:
np.dstack([c1,c2]) #2개의 3x4 -> 1개의 3x4x2

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [118]:
(np.dstack([c1,c2])).shape

(3, 4, 2)

In [119]:
c = np.stack([c1,c2]) #2개의 3x4 -> 1개의 2x3x4

In [120]:
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [121]:
c.shape

(2, 3, 4)

# 2차원 그리드 포인트

In [164]:
import matplotlib.pyplot as plt

In [165]:
x = np.arange(3)
x

array([0, 1, 2])

In [166]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [167]:
X,Y = np.meshgrid(x,y)

In [168]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [169]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [170]:
[list(zip(x,y)) for x,y in zip(X,Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [172]:
plt.title("np.meshgrid로 만든 Grid Points")
plt.scatter(X,Y, linewidths = 10)
plt.show()

TypeError: 'numpy.ndarray' object is not callable

<Figure size 432x288 with 0 Axes>