In [1]:
import numpy as np

In [2]:
x = np.arange(1,10001)
y = np.arange(10001,20001)

In [3]:
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i] + y[i]

In [4]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [5]:
z = x + y

In [6]:
z[:10]

array([10002, 10004, 10006, 10008, 10010, 10012, 10014, 10016, 10018,
       10020])

In [7]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])

In [8]:
a == b

array([False,  True, False,  True])

In [9]:
a >= b

array([False,  True,  True,  True])

In [10]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [11]:
np.all(a == b)

False

In [12]:
np.all(a == c)

True

In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [16]:
10 ** a

array([    1,    10,   100,  1000, 10000], dtype=int32)

In [17]:
np.log(a + 1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

## 스칼라와 벡터 / 행렬의 곱

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
100 * x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [21]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
100 * x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

## Broadcasting

In [26]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [25]:
y = np.ones_like(x)
y

array([1, 1, 1, 1, 1])

In [27]:
x + y

array([1, 2, 3, 4, 5])

In [28]:
x + 1

array([1, 2, 3, 4, 5])

In [29]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [30]:
y = np.arange(5)[:, np.newaxis]
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [31]:
x + y

array([[ 0,  1,  2],
       [ 2,  3,  4],
       [ 4,  5,  6],
       [ 6,  7,  8],
       [ 8,  9, 10]])

In [32]:
y = np.arange(3)
y

array([0, 1, 2])

In [33]:
x + y

array([[0, 2, 4],
       [1, 3, 5],
       [2, 4, 6],
       [3, 5, 7],
       [4, 6, 8]])

## 차원 축소 연산

In [34]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [35]:
np.sum(x)

10

In [36]:
x.sum()

10

In [37]:
x = np.array([1,3,2])

In [39]:
x.min()

1

In [40]:
x.max()

3

In [41]:
x.argmin() #최솟값의 위치

0

In [42]:
x.argmax()

1

In [43]:
x = np.array([1,3,2,1])

In [44]:
x.mean()

1.75

In [45]:
np.median(x)

1.5

In [46]:
np.all([True, True, False])

False

In [47]:
np.any([True, True, False])

True

In [48]:
a = np.zeros((100,100), dtype = np.int)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [49]:
np.any(a != 0)

False

In [50]:
np.all(a == a)

True

In [51]:
x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [52]:
x.sum()

6

In [53]:
x.sum(axis = 0) #열 합계

array([3, 3])

In [54]:
x.sum(axis = 1) #행 합계

array([2, 4])

In [56]:
b = np.ones((5,6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [58]:
b.mean()

1.0

In [59]:
b.sum()

30.0

In [60]:
b.mean(axis = 0)

array([1., 1., 1., 1., 1., 1.])

In [61]:
b.sum(axis = 1)

array([6., 6., 6., 6., 6.])

# Sort

In [64]:
a = np.array([[4, 3, 5, 7],
              [1, 12, 11, 9],
              [2, 15, 1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [65]:
np.sort(a) #axis = 1 과 동일 = 행 오름차순 정리

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [66]:
np.sort(a, axis = 0) # 열 오름차순 정리

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [67]:
a.sort(axis = 1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [68]:
a = np.array([42,38,12,25]) #순서
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [69]:
a[j]

array([12, 25, 38, 42])

In [70]:
np.sort(a)

array([12, 25, 38, 42])

In [73]:
a = np.array([[1,2,3,4],
         [46,99,100,71],
         [81,59,90,100]])

In [74]:
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [76]:
a.sort(1)

In [77]:
a

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [79]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [80]:
a = np.zeros(10)

In [81]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [84]:
a[4] = 1

In [85]:
a

array([0., 0., 0., 0., 1., 1., 0., 0., 0., 0.])

In [86]:
a[5] = 0

In [87]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [88]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [90]:
np.array([[0,1,2],
        [3,4,5],
        [6,7,8]])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [95]:
a = np.random.rand(3,3)
a

array([[0.43728085, 0.32307372, 0.68172426],
       [0.03560474, 0.86183789, 0.92406616],
       [0.72308666, 0.97479067, 0.766415  ]])

In [96]:
a.max()

0.9747906660694676

In [97]:
a.min()

0.0356047431528127

In [98]:
a.mean(axis = 1)

array([0.48069295, 0.6071696 , 0.82143078])

In [99]:
a.mean(axis = 0)

array([0.39865742, 0.71990076, 0.79073514])

In [103]:
np.random.seed(0) #시드 설정

In [101]:
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [104]:
np.random.rand(3,3)

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276]])

In [105]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
np.random.shuffle(x)
x

array([5, 2, 3, 4, 9, 0, 8, 7, 6, 1])