In [1]:
import numpy as np

In [3]:
#1차원 array
a1 = np.array([1,2,3])
print(a1)

[1 2 3]


In [4]:
#2차원
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [7]:
#3차원
a3 = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [7,8,9]]])
print(a3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


In [11]:
c = np.arange(0,15,1)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [12]:
#배열을 3행 5열로 바꾸겟다
c = c.reshape(3,5)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
d = np.arange(0, 100, 5)
print(d)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [21]:
d = d.reshape(4,1,5)
print(d)

[[[ 0  5 10 15 20]]

 [[25 30 35 40 45]]

 [[50 55 60 65 70]]

 [[75 80 85 90 95]]]


# 스칼라 연산

In [23]:
n1 = np.array([[1,0],
               [0,1]])

n2 = np.array([[1,2],
               [3,4]])

In [24]:
n1 + n2

array([[2, 2],
       [3, 5]])

In [25]:
n1 - n2

array([[ 0, -2],
       [-3, -3]])

In [26]:
n1 * n2    # 스칼라 곱(행렬 연산 x)

array([[1, 0],
       [0, 4]])

In [27]:
n1 / n2  #같은 위치 원소끼리 나눔

array([[1.  , 0.  ],
       [0.  , 0.25]])

In [28]:
n1 + 1

array([[2, 1],
       [1, 2]])

# 벡터 연산

In [30]:
np.dot(n1,n2)   #벡터의 곱연산

array([[1, 2],
       [3, 4]])

In [31]:
#열 끼리 연산 - axis = 0
#행 끼리 연산 - axis = 1

In [32]:
n3 = np.arange(12).reshape(3,4)
print(n3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [33]:
n3.sum(axis = 0)  #열 끼리 합산

array([12, 15, 18, 21])

In [34]:
n3.sum(axis = 1)

array([ 6, 22, 38])

In [35]:
n3.max(axis = 0)

array([ 8,  9, 10, 11])

In [36]:
n3.mean(axis = 1)

array([1.5, 5.5, 9.5])

In [38]:
n3.sum()

66

In [40]:
n3.cumsum() #누적합

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66], dtype=int32)

In [41]:
n3.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [43]:
v = np.array([[11,12,13,14,15],
              [21,22,23,24,25],
              [31,32,33,34,35],
              [41,42,43,44,45]])
print(v)

[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]]


In [45]:
v[1,2] #2행 3열의 데이터 추출(파이썬은 0부터 시작)

23

In [46]:
v[1][2]

23

In [48]:
v[:,1] # 전체행에서 2열 데이터 추출

array([12, 22, 32, 42])

In [49]:
v[:,3]

array([14, 24, 34, 44])

In [50]:
v[1:3,1]

array([22, 32])

In [52]:
v[1,:] #2행 전체 데이터

array([21, 22, 23, 24, 25])

# Pandas

In [53]:
#1차원 데이터 - Series
#2차원 데이터 - DataFrame

In [54]:
import pandas as pd

In [55]:
prices = [1000, 1020, 1040]

In [60]:
dates = pd.date_range('20181201', periods = 3) #날짜 생성-3일자
dates

DatetimeIndex(['2018-12-01', '2018-12-02', '2018-12-03'], dtype='datetime64[ns]', freq='D')

In [63]:
pd.date_range('20180101', '20180131', freq='W')

DatetimeIndex(['2018-01-07', '2018-01-14', '2018-01-21', '2018-01-28'], dtype='datetime64[ns]', freq='W-SUN')

In [64]:
s = pd.Series(prices, dates)

In [65]:
s

2018-12-01    1000
2018-12-02    1020
2018-12-03    1040
Freq: D, dtype: int64

In [66]:
s2 = pd.Series(prices)

In [67]:
s2

0    1000
1    1020
2    1040
dtype: int64

In [68]:
s2[3] = 1070

In [69]:
s2

0    1000
1    1020
2    1040
3    1070
dtype: int64

In [70]:
s[pd.to_datetime('2018-12-04')] = 1030
s

2018-12-01    1000
2018-12-02    1020
2018-12-03    1040
2018-12-04    1030
Freq: D, dtype: int64

In [74]:
s[2] #리스트와 같이 특정 데이터 추출 가능(배열로)

1040

In [75]:
s['2018-12-02'] #인덱스를 이용한 데이터 추출

1020

In [76]:
prices = {'삼성전자': [1000,1010,1020],
           'LG화학':[2000,2010,2020],
           '신한금융': [3000,3010,3020]}
df1 = pd.DataFrame(prices)
df1

삼성전자  LG화학  신한금융
0  1000  2000  3000
1  1010  2010  3010
2  1020  2020  3020

In [77]:
df2 = pd.DataFrame(prices, index = dates)
df2

삼성전자  LG화학  신한금융
2018-12-01  1000  2000  3000
2018-12-02  1010  2010  3010
2018-12-03  1020  2020  3020

In [79]:
df2.iloc[0] #위치정보 -> 데이터프레임 조회

삼성전자    1000
LG화학    2000
신한금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [82]:
df2.iloc[:,0] #열 전체 선택

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: 삼성전자, dtype: int64

In [83]:
df2.iloc[0,0]

1000

In [84]:
df2.loc['2018-12-01']

삼성전자    1000
LG화학    2000
신한금융    3000
Name: 2018-12-01 00:00:00, dtype: int64

In [86]:
df2.loc[:,'삼성전자']   #열 레이블만 생략 가능

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: 삼성전자, dtype: int64

In [87]:
df2.loc['2018-12-02', 'LG화학']

2010

In [88]:
df2['삼성전자']

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: 삼성전자, dtype: int64

In [90]:
df2.삼성전자

2018-12-01    1000
2018-12-02    1010
2018-12-03    1020
Freq: D, Name: 삼성전자, dtype: int64

In [91]:
df2['YG엔터'] = [100,200,300]
df2

삼성전자  LG화학  신한금융  YG엔터
2018-12-01  1000  2000  3000   100
2018-12-02  1010  2010  3010   200
2018-12-03  1020  2020  3020   300

In [92]:
df2['SK텔레콤'] = s
df2

삼성전자  LG화학  신한금융  YG엔터  SK텔레콤
2018-12-01  1000  2000  3000   100   1000
2018-12-02  1010  2010  3010   200   1020
2018-12-03  1020  2020  3020   300   1040

In [93]:
s.name = '엔씨소프트'
s

2018-12-01    1000
2018-12-02    1020
2018-12-03    1040
2018-12-04    1030
Freq: D, Name: 엔씨소프트, dtype: int64

In [96]:
df2 = pd.concat([df2,s], axis = 1)   #pd.concat([기존 데이터프레임, 시리즈],열)

In [97]:
df2

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤  엔씨소프트  엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0   1000   1000
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0   1020   1020
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0   1040   1040
2018-12-04     NaN     NaN     NaN    NaN     NaN   1030   1030

In [98]:
df3 = df2.iloc[0]
df3 = df3 + 60
df3.name = pd.to_datetime('20181207')
df3

삼성전자     1060.0
LG화학     2060.0
신한금융     3060.0
YG엔터      160.0
SK텔레콤    1060.0
엔씨소프트    1060.0
엔씨소프트    1060.0
Name: 2018-12-07 00:00:00, dtype: float64

In [99]:
df2 = df2.append(df3)
df2

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04     NaN     NaN     NaN    NaN     NaN  1030.0  1030.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0

In [101]:
df3 = df2.iloc[0] + 50
df3.name = pd.to_datetime('20181206')
df2 = df2.append(df3)
df2

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04     NaN     NaN     NaN    NaN     NaN  1030.0  1030.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0
2018-12-06  1050.0  2050.0  3050.0  150.0  1050.0  1050.0  1050.0

In [102]:
df2 = df2.sort_index(axis = 0) #sort_index -> 열을 중심으로 정렬
df2

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04     NaN     NaN     NaN    NaN     NaN  1030.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  150.0  1050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0

In [103]:
df2.fillna(0)

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04     0.0     0.0     0.0    0.0     0.0  1030.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  150.0  1050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0

In [105]:
df2.fillna(method='ffill') #NaN 을 앞의 값으로 채움

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04  1020.0  2020.0  3020.0  300.0  1040.0  1030.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  150.0  1050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0

In [106]:
df2.fillna(method='bfill') #뒤의 데이터로 채움

삼성전자    LG화학    신한금융   YG엔터   SK텔레콤   엔씨소프트   엔씨소프트
2018-12-01  1000.0  2000.0  3000.0  100.0  1000.0  1000.0  1000.0
2018-12-02  1010.0  2010.0  3010.0  200.0  1020.0  1020.0  1020.0
2018-12-03  1020.0  2020.0  3020.0  300.0  1040.0  1040.0  1040.0
2018-12-04  1050.0  2050.0  3050.0  150.0  1050.0  1030.0  1030.0
2018-12-06  1050.0  2050.0  3050.0  150.0  1050.0  1050.0  1050.0
2018-12-07  1060.0  2060.0  3060.0  160.0  1060.0  1060.0  1060.0